version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'

  my_plans_api: &my_plans_api
    build: my_plans_api
    tty: true
    stdin_open: true
    command: bash start.sh
    volumes:
      - ./my_plans_api:/my_plans_api
    ports:
      - 3030:3030
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
