# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in backup_retention_plan.gemspec
gemspec

gem "byebug", "~> 9.0", ">= 9.0.6"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"
