source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem 'backup_retention_plan', '~> 1.0'

group :development, :test do
  gem 'rspec-rails', '~> 4.0'
  gem 'database_cleaner'
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'shoulda-matchers', require: false
  gem 'pry'
  gem 'faker'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'rubocop-rails'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
